spring:
#Configurations for the Data Source - Companies microservice
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/companies-db
    username: postgres
    password: 123456789
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

# Configuration for Eureka Client
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/